### ISSUE TITLE
Create ASYNC get request for downloading files

### ISSUE THREAD

**Issue by rlowies** [johiatt/jTorrent#4]
Relates to #3  where the get request was implemented.

## Description
We want to be able to download a file for a long period of time:

The most common implementation is the one in which we buffer the bytes when performing the read/write operations. This implementation is safe to use even for large files because we don't load the whole file into memory.

This should be added to the UrlTools.java class

## AC
- [x] Clean getRequest and add HTTPS #5 
- [x] Include at least one test that successfully downloads a small file from some web host. #7, #8 
- [x] SLF4J error in console and add logger for error reporting [#8.5](https://github.com/johiatt/jTorrent/commit/06862617e0d1e03236cf55e328e5f6e5aea2e3e1)
- [ ] Research SSL for our purpose and implement necessary functionality.
- [ ] Add legitimate identity #6 
- [ ] Add timeout logic and retry if something bad happens
- [ ] Include test over SSL, timeout, and retry logic
- [x] Add support for UDP protocols #9 

## Resources
https://www.baeldung.com/java-download-file
https://www.baeldung.com/httpclient-ssl
https://www.baeldung.com/udp-in-java
https://github.com/eugenp/tutorials/tree/master/core-java-modules/core-java-networking-2
